# Day 3 — Python for AI: Libraries & Practice

**Duration:** ~2 hours
**Topics:** NumPy · Pandas · Reading CSV files · Data Exploration · Mini Project

---

By the end of this notebook you will be able to:
- Create and manipulate NumPy arrays, and understand why they're faster than lists
- Build and explore Pandas DataFrames
- Load a real CSV dataset
- Use `.head()`, `.describe()`, `.info()`, `.shape` to understand a dataset
- Complete a mini project answering real questions from data

## Part 1 — NumPy Arrays and Operations (≈20 min)

### 1.1 Why NumPy?

Python lists are flexible but slow for numerical work. **NumPy** gives us
arrays that are fast, memory-efficient, and support vectorized math —
meaning operations apply to *every element at once*, without writing loops.

In [ ]:
import numpy as np

# Creating arrays
list_a = [1, 2, 3, 4, 5]
array_a = np.array(list_a)

print("Python list:", list_a)
print("NumPy array:", array_a)
print("Type:", type(array_a))

Python list: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>

### 1.2 Vectorized Math vs. Loops

Try adding 10 to every element — the "list way" vs. the "NumPy way".

In [ ]:
# The "list way" (needs a loop)
list_result = [x + 10 for x in list_a]
print("List result:", list_result)

# The "NumPy way" (no loop needed!)
array_result = array_a + 10
print("Array result:", array_result)

# Other vectorized operations
print("Multiply by 2:", array_a * 2)
print("Square each element:", array_a ** 2)
print("Sum:", array_a.sum())
print("Mean:", array_a.mean())
print("Max:", array_a.max())

List result: [11, 12, 13, 14, 15]
Array result: [11 12 13 14 15]
Multiply by 2: [ 2  4  6  8 10]
Square each element: [ 1  4  9 16 25]
Sum: 15
Mean: 3.0
Max: 5

### 1.3 Indexing, Slicing & 2D Arrays

NumPy arrays support the same slicing syntax as lists, plus multi-dimensional indexing.

In [ ]:
# Indexing and slicing (same as lists)
print("First element:", array_a[0])
print("Last element:", array_a[-1])
print("First three:", array_a[:3])

# 2D arrays (like a matrix / grid of numbers)
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print("\nMatrix:\n", matrix)
print("Shape:", matrix.shape)        # (rows, columns)
print("Element at row 1, col 2:", matrix[1, 2])
print("Entire first row:", matrix[0, :])
print("Entire second column:", matrix[:, 1])

First element: 1
Last element: 5
First three: [1 2 3]

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Element at row 1, col 2: 6
Entire first row: [1 2 3]
Entire second column: [2 5 8]

### 1.4 Broadcasting

NumPy can apply operations between arrays of different shapes — this is called
**broadcasting**. It's one of the most powerful (and AI-relevant) features of NumPy.

In [ ]:
# Broadcasting: add a 1D array to every row of a 2D array
row_addition = np.array([10, 20, 30])
print("Matrix:\n", matrix)
print("\nAdd [10, 20, 30] to every row:\n", matrix + row_addition)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Add [10, 20, 30] to every row:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

### 🧪 Try It Yourself

1. Create a NumPy array of the numbers 1 to 10.
2. Multiply every element by 3.
3. Find the mean and the maximum of the result.

In [ ]:
# Your code here

## Part 2 — Pandas DataFrames (≈40 min)

### 2.1 What is Pandas?

**Pandas** is built on top of NumPy and gives us **DataFrames** — table-like
structures (think Excel spreadsheets) that are perfect for working with real-world data.

In [ ]:
import pandas as pd

# Creating a DataFrame from a dictionary
data = {
    "name": ["Aarav", "Diya", "Kabir", "Meera"],
    "subject": ["Math", "Math", "Science", "Math"],
    "score": [78, 92, 65, 88]
}

df = pd.DataFrame(data)
print(df)

    name  subject  score
0  Aarav     Math     78
1   Diya     Math     92
2  Kabir  Science     65
3  Meera     Math     88

### 2.2 Series vs. DataFrame

A single column of a DataFrame is called a **Series**.

In [ ]:
# A single column is a Series
scores = df["score"]
print(type(scores))
print(scores)

<class 'pandas.core.series.Series'>
0    78
1    92
2    65
3    88
Name: score, dtype: int64

### 2.3 Selecting Rows and Columns — `.loc` and `.iloc`

- `.loc[]` selects by **label** (column name, index label)
- `.iloc[]` selects by **integer position**

In [ ]:
# Selecting columns
print("Single column:\n", df["name"])
print("\nMultiple columns:\n", df[["name", "score"]])

# Selecting rows by position
print("\nFirst row (.iloc):\n", df.iloc[0])

# Selecting rows by label/condition (.loc)
print("\nStudents with score > 70:\n", df.loc[df["score"] > 70])

Single column:
 0    Aarav
1     Diya
2    Kabir
3    Meera
Name: name, dtype: object

Multiple columns:
     name  score
0  Aarav     78
1   Diya     92
2  Kabir     65
3  Meera     88

First row (.iloc):
 name       Aarav
subject     Math
score         78
Name: 0, dtype: object

Students with score > 70:
     name subject  score
0  Aarav    Math     78
1   Diya    Math     92
3  Meera    Math     88

### 🧪 Try It Yourself

1. Add a new column called `passed` that is `True` if `score >= 70`, else `False`.
   *(Hint: `df["passed"] = df["score"] >= 70`)*
2. Select only the rows where `subject == "Math"`.

In [ ]:
# Your code here

## Part 3 — Reading CSV Files (≈15 min)

### 3.1 Loading Real Data

Most real-world data comes as **CSV files**. Pandas makes loading them trivial
with `pd.read_csv()`.

We'll use `students.csv` — a small dataset of 15 students with their subject,
score, study hours, and city.

In [ ]:
# Load the CSV file
df = pd.read_csv("/content/drive/MyDrive/AI/students.csv")
df

    student_id     name  subject  score  study_hours       city
0            1    Aarav     Math     78            3    Chennai
1            2     Diya     Math     92            5     Mumbai
2            3    Kabir  Science     65            2      Delhi
3            4    Meera     Math     88            4    Chennai
4            5    Rohan  Science     73            3     Mumbai
5            6   Ishita  English     95            6  Bangalore
6            7   Vivaan     Math     55            1      Delhi
7            8   Ananya  Science     82            4    Chennai
8            9   Aditya  English     67            2     Mumbai
9           10   Saanvi     Math     99            6  Bangalore
10          11  Krishna  Science     71            3      Delhi
11          12     Riya  English     84            5    Chennai
12          13    Arjun     Math     60            2     Mumbai
13          14     Tara  Science     90            5  Bangalore
14          15     Yash  English     77            3      Delhi

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

> 💡 If you're running this notebook elsewhere, make sure `students.csv`
> is in the same folder, or update the path above.

## Part 4 — Basic Data Exploration (≈15 min)

Before doing anything with a dataset, **always explore it first**. Four
go-to methods:

| Method | What it tells you |
|---|---|
| `.head()` | First few rows — a quick look |
| `.shape` | (rows, columns) — size of the dataset |
| `.info()` | Column names, data types, missing values |
| `.describe()` | Statistical summary (mean, min, max, etc.) |

In [ ]:
# First 5 rows
df.head()

   student_id   name  subject  score  study_hours     city
0           1  Aarav     Math     78            3  Chennai
1           2   Diya     Math     92            5   Mumbai
2           3  Kabir  Science     65            2    Delhi
3           4  Meera     Math     88            4  Chennai
4           5  Rohan  Science     73            3   Mumbai

In [ ]:
# Shape: (rows, columns)
print("Shape:", df.shape)

Shape: (15, 6)

In [ ]:
# Column info: names, types, non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   15 non-null     int64
 1   name         15 non-null     object
 2   subject      15 non-null     object
 3   score        15 non-null     int64
 4   study_hours  15 non-null     int64
 5   city         15 non-null     object
dtypes: int64(3), object(3)
memory usage: 852.0+ bytes

In [ ]:
# Statistical summary of numeric columns
df.describe()

       student_id      score  study_hours
count   15.000000  15.000000    15.000000
mean     8.000000  78.400000     3.600000
std      4.472136  13.195237     1.549193
min      1.000000  55.000000     1.000000
25%      4.500000  69.000000     2.500000
50%      8.000000  78.000000     3.000000
75%     11.500000  89.000000     5.000000
max     15.000000  99.000000     6.000000

In [ ]:
# Check for missing values
df.isnull().sum()

student_id     0
name           0
subject        0
score          0
study_hours    0
city           0
dtype: int64

## Part 5 — Mini Project: Student Performance Analysis (≈45 min)

### 🎯 Your Task

Using the `students.csv` dataset, answer the following questions using Pandas.
Write your code in the cells below each question.

**Dataset reminder — columns:**
`student_id, name, subject, score, study_hours, city`

---
**Q1.** What is the average score across all students?

In [ ]:
# Q1: Average score

---
**Q2.** Which student has the highest score? Print their name and score.

*Hint: use `.max()` to find the highest score, then filter the DataFrame for that row.*

In [ ]:
# Q2: Student with the highest score

---
**Q3.** What is the average score **per subject**?

*Hint: use `df.groupby("subject")["score"].mean()`*

In [ ]:
# Q3: Average score per subject

---
**Q4.** Is there a relationship between `study_hours` and `score`?
Calculate the correlation between the two columns.

*Hint: `df["study_hours"].corr(df["score"])`*

In [ ]:
# Q4: Correlation between study hours and score

---
**Q5.** Create a new column `grade` based on `score`:
- `score >= 90` → "A"
- `score >= 75` → "B"
- `score >= 60` → "C"
- below 60 → "D"

*Hint: write a function and use `df["score"].apply(your_function)`*

In [ ]:
# Q5: Add a 'grade' column
def get_grade(score):
    # your logic here
    pass

# df["grade"] = df["score"].apply(get_grade)
# df

---
**Q6 (Bonus).** Which city has the most students scoring grade "A"?

In [ ]:
# Q6 (Bonus): City with most 'A' grades

## Wrap-Up

Today you learned:
- ✅ NumPy arrays and vectorized operations (no more loops for math!)
- ✅ Pandas DataFrames and Series
- ✅ Selecting data with `.loc` and `.iloc`
- ✅ Reading real CSV files with `pd.read_csv()`
- ✅ Exploring a dataset with `.head()`, `.shape`, `.info()`, `.describe()`
- ✅ Applied everything in a mini project

### Next session (Day 4): Introduction to Artificial Intelligence
We'll zoom out from code and explore the history, scope, and key ideas
that define the field of AI.